### ISSUE TITLE
Add API

### ISSUE THREAD

**Issue by webmaster128** [UCRegistry/registry#21]
I propose an API in the form of static json files. A new `dist/v1` folder should contain the following:

1. `dist/v1/all.json`, `dist/v1/evm.json` and `dist/v1/cosmos.json` are exported as they are
2. `dist/v1/networks/<networdId>.json` allows accessing the individual files directly
3. `dist/v1/index.json` contains a new search index with name and network ID only (See `jq -c 'map({ name, networkId })' < chains.json`)

All files are minified and can be served gzipped using static webosting. The `index.json` gzipped is only ~14 bytes per chain in size, so even with 10 thousand chains this would just be 140 KB to download. 

With static files only, this is super simple to deploy. We can serve this via a static file hoster (or have multiple mirrors if necessary) and in addition, we can publish the same dist folder to in an npm package, allowing applications to access the data locally.

@RiccardoM would this serve your needs?

**Comment by RiccardoM** [comment]
@webmaster128 Thank you for opening this up! This would be indeed sufficient for everything in the first place. 

In the future we could expand this by implementing GraphQL endpoints too.

**Comment by webmaster128** [comment]
https://universal-chain-registry.firebaseapp.com/v1/index.json
https://universal-chain-registry.firebaseapp.com/v1/all.json
https://universal-chain-registry.firebaseapp.com/v1/cosmos.json
https://universal-chain-registry.firebaseapp.com/v1/evm.json
https://universal-chain-registry.firebaseapp.com/v1/networks/eip155-1.json

Is an example deployment of what I described above. We could add multiple mirriors if we want and of our own domain.
