### ISSUE TITLE
Add "node_source" field

### ISSUE THREAD

**Issue by pedrouid** [UCRegistry/registry#7]
This new field is part of the initiative to incentivize applications to run their nodes instead of relying on remote nodes thus "client_src" references where the client source code can be download from.

There should be a discussion about what requirements these references must have to be valid to be added to this registry

**Comment by webmaster128** [comment]
Thanks for explaining the motivation, this really helps. Given this, I think the term "client" is misleading as it implies a software connecting to the blockchain. What about "node source"?

**Comment by pedrouid** [comment]
Sounds good to me. Let's change it to "node_source"

**Comment by webmaster128** [comment]
Is this supposed to me machine-processable in the sense that it allows for automatic node spawning?

1. If yes, we should have download source, software version and checksum/signature in the registry. This comes with the drawback that an update to the registry is necessary for every single patch release of every implementation of every network.
2. If no, we can link webpages that describe the software distribution process in a general, admin friendly way. The link should be long living.

**Comment by RiccardoM** [comment]
I think that two main things should be considered when speaking about this field: 

First, it **should not** be mandatory.  
There could be some chains that do not want to distribute their node source code (federated ones, or even private chains as a whole) 

Second, also answering @webmaster128, I think we should require the user to use a Github/Gitlab/w.e link to a specific commit that represents the software version to use.  

1. If we allow the user to insert a generic link, we cannot make sure that is a valid link and will always be (might be a redirect, or something else). 
2. If we allow the user to insert a downloadable executable, we cannot make sure that it will always be a trustworthy executable. It might start acting as a virus or something else malicious. 

Targeting developers, I think they will know how to build and deploy the node by just having two things:

1. Reference to the executable source
2. Reference to the build guide

So, I think we could expand the `node_source` field renaming it to `node_info` and having the following attributes

```json
{
 "node_info": {
   "version": "1.0.1",
   "source_code": "https://github.com/commercionetwork/commercionetwork/tree/v1.0.1",
   "build_instructions": "https://github.com/commercionetwork/commercionetwork/blob/master/docs/join-mainnet.md"
 }
}
```

Also, having an object as a field we will later be able to add additional information without much trouble.

**Comment by webmaster128** [comment]
+1 for making this optional.

With this approach I see two disadvantages at the same time:
1. An update to the registry is required for every version update of the node software
2. It is not possible to automatically spawn a node with the information provided by the registry

We should accept the fact that with URLs and redirects it is always possible to change the target to somewhere else than at the time of the PR. This can also be very good e.g. when thinking of download mirrors. Having checksums ensures nothing crazy happens.

So for me the question is still open: does this need to be machine processable? Then we should have a direct link and a checksum of the file. Otherwise build instructions are sufficient and we don't need the version in the registry, since the latest version can be available in the build instructions.

**Comment by RiccardoM** [comment]
I think this should not be machine processable. 

Some chains might not have the characteristic of having reproducible builds (such as Cosmos a few weeks ago)  and thus the checksum on the executable itself will not prevent strange things from happening. 

A link to the codebase and build instructions could be best way to go that allows to have fewer updates and prevents anything strange from happening. 

If a developer wants to automatically spawn a node, then he can create a tool to perform all the checks and different things he might want to do IMO.

**Comment by webmaster128** [comment]
Fine for me. In this case a generic link to build instructions would do the job
