### ISSUE TITLE
Add "seed_nodes" field

### ISSUE THREAD

**Issue by pedrouid** [UCRegistry/registry#8]
Also part of the initiative to incentivize application developers to run their nodes, we will include an array of bootstrap or seed nodes that are used to discover peers within the network.

This list of addresses might coincide with the hardcode values on the clients source code but ideally it would include other community support seed nodes which were not there.

**Comment by webmaster128** [comment]
+1

I've seen the desire to add community seed nodes [at Lisk](https://github.com/LiskHQ/lisk-sdk/issues/2000) but is has not yet happened in the main software. In those scenarios, such a registry can help.

**Comment by RiccardoM** [comment]
> we will include an array of bootstrap or seed nodes that are used to discover peers within the network

A point brought up during the discussion was: how can we make sure those nodes are safe and do not act as malicious ones? Also, should we make this information mandatory? I really think that there could be some chains not wanting to spread such information (maybe federated ones or ones that do not care in having other nodes) so we should not enforce to give such information at all.

---

> This list of addresses might coincide with the hardcode values on the clients source code

Actually, Cosmos has no such a thing so I would avoid performing those kind of checks in any case.
