### ISSUE TITLE
Add coin type

### ISSUE THREAD

**Issue by pedrouid** [UCRegistry/registry#9]
Since we are listing an array of coins supported by each of these blockchains, we should include a field for the type of coin it is within its system. Specially for Cosmos chains there are many utilities that could be used for an on-chain coin like bonding, staking and others.

A more thorough discussion should be had if this field is just an arbitrary string or an enum

**Comment by RiccardoM** [comment]
### About enums or free strings values
I think this is going to be quite tricky is we let everyone specify arbitrary string. 

Let's take as an example what might happen inside a Cosmos chain. You could have
* a default coins (which can be bonded) 
* `n` other coins (which cannot be bonded)

If we let the user specify the type of the bondable one, what should he use? The options could be `default`, `stakable`, `bondable`, etc. 

I think that we should define an enum based on the network type (either `cosmos` or `evm` right now) and allow the coin type to be only one of those enum values. 

### About non-mutually exclusive types
Also, how do we allow users to specify multiple types? I think that coin types could represents things that are not mutually exclusive. For example, I could want to use to types as follows:

* `unlocked` for a coin that can be send 
* `locked` for a coin that can be send

Having a simple string field, how could be represents a bondable coin that cannot be send? This could lead to further complications. 

### Solution
#### Coin type
I think we should define the `type` field as follows: 

| Field | Type | Description | 
| :---- | :--------- | :---------- |
| `type` | `[]string` | Contains the list of identifiers describing the type of the related coin |

#### Coins field
We also should expand the `coins` field making it an object allowing for default types to be applied for all the coins 

```json
{
  "coins": {
    "default_types": [
      "sendable"
    ],
    "list": [
      {
        "name": "Atom",
        "symbol": "ATM",
        "denom": "uatom",
        "types": [
          "bondable"
        ],
        "exponent": 6
      },
      {
        "name": "Photino",
        "symbol": "PTN",
        "denom": "uphotino",
        "types": [],
        "exponent": 6
      }
    ]
  }
}
```

This would allow to define default types as well as supporting multiple types without many troubles.

**Comment by RiccardoM** [comment]
I would love to hear the feedback to this from @webmaster128 as well

**Comment by webmaster128** [comment]
I was thinking in the same direction (feature flags), but more like:

```json
{
  "coins": {
    "default_types": [
      "sendable"
    ],
    "list": [
      {
        "name": "Atom",
        "symbol": "ATM",
        "denom": "uatom",
        "flags": {
          "bondable": true
        },
        "exponent": 6
      },
      {
        "name": "Photino",
        "symbol": "PTN",
        "denom": "uphotino",
        "flags": {},
        "exponent": 6
      }
    ]
  }
}
```

However, I think both approaches are equal.

**Comment by RiccardoM** [comment]
I think I would go with an array for the `flags` property, as it could be easier to check if an attribute is listed or no. However I don't have a strong opinion about this. Maybe we can see what @pedrouid thinks about it.

**Comment by pedrouid** [comment]
I would also signal to use an array too
